export const categoryIconMap: Record<string, string> = {
  beauty: "face-woman",
  fragrances: "spray",
  furniture: "sofa",
  groceries: "cart",
  "home-decoration": "home-outline",
  "kitchen-accessories": "silverware-fork-knife",
  laptops: "laptop",
  "mens-shirts": "tshirt-crew",
  "mens-shoes": "shoe-formal",
  "mens-watches": "watch",
  "mobile-accessories": "earbuds",
  motorcycle: "motorbike",
  "skin-care": "hand-heart",
  smartphones: "cellphone",
  "sports-accessories": "dumbbell",
  sunglasses: "sunglasses",
  tablets: "tablet",
  tops: "hanger",
  vehicle: "car",
  "womens-bags": "bag-personal",
  "womens-dresses": "human-female",
  "womens-jewellery": "diamond-stone",
  "womens-shoes": "shoe-heel",
  "womens-watches": "watch-variant",
};
